ycms/cms/models/patient.py
from datetime import datetime

from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from ..constants import gender, insurance_types, record_types
from .abstract_base_model import AbstractBaseModel
from .timetravel_manager import current_or_travelled_time, TimetravelManager
from .user import User


class Patient(AbstractBaseModel):
    """
    Data model representing a Patient.
    """

    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=current_or_travelled_time, null=False)
    updated_at = models.DateTimeField(auto_now=True, null=False)
    insurance_type = models.BooleanField(
        verbose_name=_("insurance type"),
        help_text=_("Whether the patient is privately insured or not"),
        choices=insurance_types.CHOICES,
        default=insurance_types.STATUTORY,
    )
    first_name = models.CharField(
        max_length=32,
        verbose_name=_("first name"),
        help_text=_("First name of the patient"),
    )
    last_name = models.CharField(
        max_length=64,
        verbose_name=_("last name"),
        help_text=_("Last name of the patient"),
    )
    gender = models.CharField(
        max_length=1,
        choices=gender.CHOICES,
        verbose_name=_("gender"),
        help_text=_("Gender of the patient"),
        default=None,
    )
    date_of_birth = models.DateField(
        verbose_name=_("date of birth"), help_text=_("Date of birth of the patient")
    )
    _first = models.CharField(max_length=32, blank=True)
    _last = models.CharField(max_length=64, blank=True)

    objects = TimetravelManager()

    @cached_property
    def age(self):
        """
        Helper property to get the patient's age in years

        :return: the patient's age in years
        :rtype: int
        """
        today = datetime.today().date()
        years_ago = today.year - self.date_of_birth.year
        if today.month < self.date_of_birth.month or (
            today.month == self.date_of_birth.month
            and today.day < self.date_of_birth.day
        ):
            return max(0, years_ago - 1)
        return max(0, years_ago)

    @cached_property
    def insurance_name(self):
        """
        Helper property to get the human-readable representation of the patient's
        insurance type
        """
        return dict(insurance_types.CHOICES)[self.insurance_type]

    @cached_property
    def short_info(self):
        """
        Helper property to get a short info string about the patient

        :return: the patient's info as a short string
        :rtype: str
        """
        age = _("age")
        insurance = _("insurance")
        return f"{self.first_name[0]}. {self.last_name} ({age}: {self.age}, {insurance}: {self.insurance_name})"

    @cached_property
    def current_stay(self):
        """
        Helper property for accessing the patient's current hospital stay

        :return: the current bed assignment
        :rtype: ~ycms.cms.models.bed_assignment.BedAssignment
        """
        hospital_stay = self.medical_records.filter(
            models.Q(record_type=record_types.INTAKE)
            & models.Q(bed_assignment__admission_date__lte=current_or_travelled_time())
            & (
                models.Q(bed_assignment__discharge_date__isnull=True)
                | models.Q(
                    bed_assignment__discharge_date__gt=current_or_travelled_time()
                )
            )
        ).first()
        return hospital_stay.bed_assignment.get() if hospital_stay else None

    @cached_property
    def current_bed(self):
        """
        Helper property for accessing the patient's current bed

        :return: the current bed
        :rtype: ~ycms.cms.models.bed.Bed
        """
        return self.current_stay.bed if self.current_stay else None

    @cached_property
    def current_room(self):
        """
        Helper property for accessing the patient's current room

        :return: the current room
        :rtype: ~ycms.cms.models.room.Room
        """
        return self.current_bed.room if self.current_bed else None

    @cached_property
    def current_ward(self):
        """
        Helper property for accessing the patient's current ward

        :return: the current ward
        :rtype: ~ycms.cms.models.ward.Ward
        """
        return self.current_room.ward if self.current_room else None

    @staticmethod
    def _get_date_status(date_to_check):
        """
        Helper function to get the date status of a given date

        :param date_to_check: the date to check
        :type date_to_check: datetime.date
        :return: the date status
        :rtype: str
        """
        if not date_to_check:
            return None

        today = _("today")
        days_ago = _("{} days ago")
        day_ago = _("{} day ago")
        in_days = _("in {} days")
        in_day = _("in {} day")

        if not (
            days_since := (
                current_or_travelled_time().date() - date_to_check.date()
            ).days
        ):
            return f'{date_to_check.strftime("%b. %d, %Y")} ({today})'

        if days_since > 0:
            return f"{date_to_check.strftime('%b. %d, %Y')} ({ day_ago.format(days_since) if days_since == 1 else days_ago.format(days_since)})"

        days_until = abs(days_since)
        return f"{date_to_check.strftime('%b. %d, %Y')} ({in_day.format(days_until) if days_until == 1 else in_days.format(days_until)})"

    @cached_property
    def current_admission_date(self):
        """
        Helper property for accessing the patient's current admission date

        :return: the current admission date
        :rtype: str
        """
        if not self.current_stay:
            return None
        return self._get_date_status(self.current_stay.admission_date)

    @cached_property
    def current_discharge_date(self):
        """
        Helper property for accessing the patient's current discharge date

        :return: the current discharge date
        :rtype: str
        """
        if not self.current_stay:
            return None
        return self._get_date_status(self.current_stay.discharge_date)

    def __str__(self):
        """
        This overwrites the default Django :meth:`~django.db.models.Model.__str__` method which would return ``Patient object (id)``.
        It is used in the Django admin backend and as label for ModelChoiceFields.

        :return: A readable string representation of the patient
        :rtype: str
        """
        return f"{self.last_name}, {self.first_name} (patient {self.id})"

    def get_repr(self):
        """
        This overwrites the default Django ``__repr__()`` method which would return ``<Patient: Patient object (id)>``.
        It is used for logging.

        :return: The canonical string representation of the patient
        :rtype: str
        """
        return f"<Patient (id: {self.id})>"

    class Meta:
        verbose_name = _("patient")
        verbose_name_plural = _("patients")

ycms/cms/models/ward.py
from django.apps import apps
from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from .abstract_base_model import AbstractBaseModel
from .patient import Patient
from .timetravel_manager import current_or_travelled_time
from .user import User


class Ward(AbstractBaseModel):
    """
    Data model representing a Ward.
    """

    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=current_or_travelled_time, null=False)
    updated_at = models.DateTimeField(auto_now=True, null=False)
    ward_number = models.CharField(
        unique=True,
        max_length=32,
        verbose_name=_("ward number"),
        help_text=_("Number of the ward"),
    )
    floor = models.IntegerField(
        verbose_name=_("floor"),
        help_text=_("Floor on which the nurse station for this ward is located"),
    )
    name = models.CharField(
        max_length=32,
        verbose_name=_("ward name"),
        help_text=_("Name this ward is commonly referred to by"),
    )

    @cached_property
    def total_beds(self):
        """
        Helper property for accessing the wards bed count

        :return: number of beds in the ward
        :rtype: int
        """
        return sum(room.total_beds for room in self.rooms.all())

    @cached_property
    def available_beds(self):
        """
        Helper property for accessing the wards free bed count

        :return: number of free beds in the ward
        :rtype: int
        """
        return sum(room.available_beds for room in self.rooms.all())

    @cached_property
    def occupied_beds(self):
        """
        Helper property for accessing the wards occupied bed count

        :return: number of occupied beds in the ward
        :rtype: int
        """
        return self.total_beds - self.available_beds

    @cached_property
    def patients(self):
        """
        Helper property for accessing all patients currently stationed in the ward

        :return: patients in the ward
        :rtype: list [ ~ycms.cms.models.patient.Patient ]
        """
        BedAssignment = apps.get_model(app_label="cms", model_name="BedAssignment")

        patient_ids = BedAssignment.objects.filter(
            models.Q(bed__room__ward=self)
            & (
                models.Q(admission_date__lte=current_or_travelled_time())
                & (
                    models.Q(discharge_date__gt=current_or_travelled_time())
                    | models.Q(discharge_date__isnull=True)
                )
            )
        ).values_list("medical_record__patient", flat=True)
        patients = Patient.objects.filter(pk__in=patient_ids)
        return patients

    def __str__(self):
        """
        This overwrites the default Django :meth:`~django.db.models.Model.__str__` method which would return ``Ward object (id)``.
        It is used in the Django admin backend and as label for ModelChoiceFields.

        :return: A readable string representation of the ward
        :rtype: str
        """
        return f"{self.name} (ward {self.ward_number})"

    def get_repr(self):
        """
        This overwrites the default Django ``__repr__()`` method which would return ``<Ward: Ward object (id)>``.
        It is used for logging.

        :return: The canonical string representation of the ward
        :rtype: str
        """
        return f"<Ward (number: {self.ward_number})>"

    class Meta:
        verbose_name = _("ward")
        verbose_name_plural = _("wards")

ycms/cms/views/user_settings_view.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render
from django.utils.translation import gettext as _
from django.views.generic import TemplateView

from ..forms import UserForm


class UserSettingsView(TemplateView):
    """
    View to see user settings
    """

    template_name = "user_settings.html"

    def get(self, request, *args, **kwargs):
        user_form = UserForm(instance=request.user)
        password_form = PasswordChangeForm(request.user)

        return render(
            request,
            self.template_name,
            {"user_form": user_form, "password_form": password_form},
        )

    def post(self, request, *args, **kwargs):
        """
        This function updates the settings
        """
        form_type = request.POST["form_type"]

        if form_type == "general":
            user_form = UserForm(data=request.POST, instance=request.user)
            if user_form.is_valid():
                user_form.save()
                messages.success(request, _("Your settings were successfully updated!"))

            password_form = PasswordChangeForm(request.user)

        if form_type == "password":
            password_form = PasswordChangeForm(request.user, request.POST)
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)
                messages.success(request, _("Your password was successfully updated!"))

            user_form = UserForm(instance=request.user)

        return render(
            request,
            self.template_name,
            {"user_form": user_form, "password_form": password_form},
        )

ycms/cms/templates/_base.html
{% extends "_raw.html" %}
{% load i18n %}
{% load static %}
{% comment %}
Copyright [2019] [Integreat Project]
Copyright [2023] [YCMS]

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}
{% block raw_content %}
    <div class="lg:flex dark:bg-gray-900 min-h-full">
        <button id="sidebarOpen" class="block lg:hidden text-gray-600 px-4 py-3">
            <i id="menuIcon" icon-name="menu"></i>
        </button>
        <div id="sidebarBackdrop"
             class="fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 z-[29] hidden"></div>
        <div id="sidebar"
             class="fixed top-0 bottom-0 h-full w-64 bg-white border-r shadow-md transform -translate-x-full lg:translate-x-0 lg:block dark:border-gray-600 overflow-y-auto z-[30]">
            <div class="absolute top-0 right-0 z-100 p-4 lg:hidden">
                <button id="sidebarClose" class="hidden" class="text-gray-600 px-4 py-3">
                    <i id="closeIcon" icon-name="x"></i>
                </button>
            </div>
            <div class="flex flex-col justify-between min-h-full">
                <a href="{% url 'cms:protected:index' %}"
                   class="block border-b dark:border-gray-600 flex items-center text-gray-600 dark:text-white">
                    {% if is_dark_theme %}
                        <img src="{% static 'images/logo-bed.svg' %}"
                             width="80px"
                             height="auto"
                             alt="{% translate " Logo" %}"
                             class="my-3 mx-3 ml-6 filter-white">
                    {% else %}
                        <img src="{% static 'images/logo-bed.svg' %}"
                             width="80px"
                             height="auto"
                             alt="{% translate " Logo" %}"
                             class="my-3 mx-3 ml-6">
                    {% endif %}
                    <div class="mt-8 text-gray-800 font-semibold text-4xl dark:text-gray-50">YCMS</div>
                </a>
                <ul>
                    <span class="block mt-2 px-5 text-gray-500 tracking-wide dark:text-gray-300">{% translate "General" %}</span>
                    {% if perms.cms.add_ward %}
                        <li>
                            {% url 'cms:protected:ward_management' as url %}
                            <a href="{{ url }}"
                               class="{% if request.path == url %}selected{% endif %}">
                                <i icon-name="activity"></i> {% translate "Ward Management" %}
                            </a>
                        </li>
                    {% endif %}
                    {% if perms.cms.change_patient %}
                        <li>
                            {% url 'cms:protected:patients' as url %}
                            <a href="{{ url }}"
                               class="{% if request.path == url %}selected{% endif %}">
                                <i icon-name="folder-search"></i> {% translate "Patient Data" %}
                            </a>
                        </li>
                    {% endif %}
                    {% if perms.cms.change_patient %}
                        <span class="block mt-5 px-5 text-gray-500 tracking-wide dark:text-gray-300">{% translate "Ward" %}</span>
                        <li>
                            {% url 'cms:protected:ward_detail_default' as url %}
                            {% url 'cms:protected:ward_management' as ward_management_url %}
                            <a href="{{ url }}"
                               class="{% if request.path != ward_management_url %}{% if '/ward/' in request.path or '/timeline/' in request.path %}selected{% endif %}{% endif %}">
                                <i icon-name="bed"></i> {% translate "Ward View" %}
                            </a>
                        </li>
                        <li>
                            {% url 'cms:protected:intake' as url %}
                            <a href="{{ url }}"
                               class="{% if request.path == url %}selected{% endif %}">
                                <i icon-name="user-plus"></i> {% translate "Patient Intake" %}
                            </a>
                        </li>
                    {% endif %}
                    <span class="block mt-5 px-5 text-gray-500 dark:text-gray-300">{% translate "Settings" %}</span>
                    {% if user.group.name != "MEDICAL_PERSONNEL" %}
                        <li>
                            {% url 'cms:protected:create_user' as url %}
                            <a href="{{ url }}"
                               class="{% if request.path == url %}selected{% endif %}">
                                <i icon-name="smile-plus"></i> {% translate "Create User" %}
                            </a>
                        </li>
                    {% endif %}
                    <li>
                        {% url 'cms:protected:settings' as url %}
                        <a href="{{ url }}"
                           class="{% if request.path == url %}selected{% endif %}">
                            <i icon-name="sliders-horizontal"></i> {% translate "Settings" %}
                        </a>
                    </li>
                    <li>
                        <a href="https://ycms.readthedocs.io/en/latest/" target="_blank">
                            <i icon-name="file-text"></i> {% translate "Documentation" %}
                        </a>
                    </li>
                    <li>
                        {% url 'cms:public:logout' as url %}
                        <a href="{{ url }}">
                            <i icon-name="log-out"></i> {% translate "Logout" %}
                        </a>
                    </li>
                </ul>
                <div class="text-center text-gray-600 w-full mt-auto">
                    <li class="mb-4" id="timetravel-start">
                        <a href="?time={% now "Y-m-d" %}T{% now "H:i:s" %}.000Z"
                           class="justify-center">
                            <i icon-name="timer-reset"></i>
                            {% translate "Start Timetravel" %}
                        </a>
                    </li>
                    <li class="hidden mb-4" id="timetravel-stop">
                        <a href="?" class="no-timetravel justify-center"><i icon-name="timer-off"></i> {% translate "Stop Timetravel" %}</a>
                    </li>
                    <div class="flex justify-center items-center mb-4 gap-4">
                        <a href="{% url 'change-theme' %}"
                           data-tooltip-target="tooltip-right"
                           data-tooltip-placement="right"
                           class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-600 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-800 rounded-lg text-sm p-2.5">
                            {% if is_dark_theme %}
                                <i icon-name="sun"></i>
                            {% else %}
                                <i icon-name="moon"></i>
                            {% endif %}
                        </a>
                        <div id="tooltip-right"
                             role="tooltip"
                             class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-gray-800 rounded-lg shadow-sm opacity-0 tooltip">
                            {% if is_dark_theme %}
                                {% translate "Turn on the light" %}
                            {% else %}
                                {% translate "Turn off the light" %}
                            {% endif %}
                            <div class="tooltip-arrow" data-popper-arrow></div>
                        </div>
                        <div class="flex items-center">
                            <form class="mr-2" action="{% url 'switch-language' 'en' %}" method="post">
                                {% csrf_token %}
                                <button type="submit"
                                        id="lang-switch-en"
                                        class="{% if request.COOKIES.django_language == 'en' %} underline pointer-events-none text-gray-300 dark:text-gray-500 {% endif %} text-gray-600 hover:text-blue-500 focus:outline-none dark:text-gray-50 dark:hover:text-gray-300">
                                    EN
                                </button>
                            </form>
                            <div class="border-l h-6"></div>
                            <form class="ml-2" action="{% url 'switch-language' 'de' %}" method="post">
                                {% csrf_token %}
                                <button type="submit"
                                        id="lang-switch-de"
                                        class="{% if request.COOKIES.django_language == 'de' %} underline pointer-events-none text-gray-300 dark:text-gray-500 {% endif %} text-gray-600 hover:text-blue-500 focus:outline-none dark:text-gray-50 dark:hover:text-gray-300">
                                    DE
                                </button>
                            </form>
                        </div>
                    </div>
                    <p class="text-sm dark:text-gray-50">
                        {% translate "Logged in as" %} <span class="text-blue-500">{{ user.first_name }} {{ user.last_name }}</span>
                    </p>
                    <p class="tracking-wide dark:text-gray-50">© YCMS 2024</p>
                </div>
            </div>
        </div>
        <div id="mainContent"
             class="flex-1 p-6 ml-0 lg:ml-64 h-full overflow-y-auto transition-transform ease-in-out duration-300">
            <div class="hidden lg:block fixed top-1/2 -ml-6 z-10">
                <button id="leftToggle"
                        data-tooltip-target="tooltip-sidebar"
                        class="opacity-50 hover:opacity-100"
                        data-tooltip-placement="right">
                    <i id="leftIcon"
                       class="flex justify-center items-center h-6 w-6 transition-all ease-in-out duration-300">
                        <span class="text-gray-400">|</span>
                    </i>
                </button>
            </div>
            <div id="tooltip-sidebar"
                 role="tooltip"
                 class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-gray-700 rounded-lg shadow-sm opacity-0 tooltip">
                {% translate "Toggle sidebar" %}
                <div class="tooltip-arrow" data-popper-arrow></div>
            </div>
            {% block content %}
            {% endblock content %}
            {% include "timetravel_controls.html" %}
        </div>
    </div>
{% endblock raw_content %}

ycms/cms/templates/_raw.html
{% load static %}
{% load i18n %}
{% load render_bundle from webpack_loader %}
{% comment %}
Copyright [2019] [Integreat Project]
Copyright [2023] [YCMS]

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}"
      class="{% if is_dark_theme %}dark{% endif %}">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, user-scalable=no" />
        <meta name="description" content="" />
        <meta name="keywords" content="ycms" />
        <title>{{ "YCMS"|title }} |
            {% block title %}
            {% endblock title %}
        </title>
        <link rel="shortcut icon"
              type="image/svg"
              href="{% static 'images/favicon.svg' %}" />
        {% render_bundle 'main' 'js' %}
        {% render_bundle 'main' 'css' %}
        {% block javascript_head %}
        {% endblock javascript_head %}
    </head>
    <body class="font-default text-lg bg-background-50">
        {% if messages and not messages_suppressed %}
            <div id="messages"
                 class="absolute md:top-8 md:right-8 flex flex-col max-w-screen-sm z-50">
                {% for msg in messages %}
                    {% if msg.level_tag == 'info' %}
                        <div class="message bg-blue-100 border-l-4 border-blue-500 dark:bg-blue-700 dark:border-blue-400"
                             role="alert">
                            <p class="!text-blue-500 dark:!text-blue-50">{{ msg.message }}</p>
                            <i icon-name="x" class="message-close"></i>
                        </div>
                    {% endif %}
                    {% if msg.level_tag == 'success' %}
                        <div class="message bg-green-100 border-l-4 border-green-500 dark:bg-green-700 dark:border-green-400"
                             role="alert">
                            <p class="!text-green-500 dark:!text-green-50">{{ msg.message }}</p>
                            <i icon-name="x" class="message-close"></i>
                        </div>
                    {% endif %}
                    {% if msg.level_tag == 'warning' %}
                        <div class="message bg-yellow-100 border-l-4 border-yellow-500 dark:bg-yellow-700 dark:border-yellow-400"
                             role="alert">
                            <p class="!text-yellow-600 dark:!text-yellow-60">{{ msg.message }}</p>
                            <i icon-name="x" class="message-close"></i>
                        </div>
                    {% endif %}
                    {% if msg.level_tag == 'error' %}
                        <div class="message bg-red-100 border-l-4 border-red-500 dark:bg-red-700 dark:border-red-400"
                             role="alert">
                            <p class="!text-red-500 dark:!text-red-50">{{ msg.message }}</p>
                            <i icon-name="x" class="message-close"></i>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <div id="loader-container" class="hidden relative">
            <div class="fixed top-0 left-0 right-0 bottom-0 bg-black/50 z-[9998]"></div>
            <div class="text-blue-800 dark:text-blue-600 fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-[9999]">
                <i icon-name="loader-2" class="w-12 h-12 animate-spin"></i>
            </div>
        </div>
        {% block raw_content %}
        {% endblock raw_content %}
        {% block javascript %}
        {% endblock javascript %}
    </body>
</html>

ycms/cms/templates/index.html
{% extends "_base.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% load render_bundle from webpack_loader %}
{% block title %}
    {% translate "Home" %}
{% endblock title %}
{% block content %}
    <div class="max-w-6xl mx-auto">
        {% if perms.cms.add_patient %}
            <form enctype="multipart/form-data"
                  method="post"
                  id="patient_form"
                  class="mb-12"
                  data-unsaved-warning>
                {% csrf_token %}
                <div class="w-full flex flex-col flex-wrap mb-6">
                    <h1 class="heading">{% translate "Add new patient" %}</h1>
                </div>
                {% with WIDGET_ERROR_CLASS="border-red-500" %}
                    {{ form }}
                    <br />
                    <button type="submit" class="btn mt-4">{% translate "Add new patient" %}</button>
                {% endwith %}
            </form>
        {% endif %}
        {% if perms.cms.view_patient %}
            <div class="w-full flex flex-col flex-wrap mb-6">
                <h1 class="heading">{% translate "Patients list" %}</h1>
            </div>
            {% for patient in patients %}
                <div class="bg-white border-2 justify-between border-gray-200 rounded-lg shadow-md shadow-inner mb-8 gap-6 overflow-hidden">
                    <div class="px-8 py-6 grow">
                        <p class="text-xl font-bold">
                            <span class="font-bold">{{ patient.last_name }}</span>, {{ patient.first_name }}
                        </p>
                        <p>
                            {% translate "Privately insured" %}:
                            {% if patient.insurance_type %}
                                <i icon-name="check" class="w-4 h-4 text-green-700"></i>
                            {% else %}
                                <i icon-name="x" class="w-4 h-4 text-red-700"></i>
                            {% endif %}
                        </p>
                        <p class="text-gray-800 mt-4">{% translate "DOB" %}: {{ patient.date_of_birth }}</p>
                        <p class="text-gray-800">{% translate "Age" %}: {{ patient.age }}</p>
                        <p class="text-gray-800 mb-4">{% translate "Gender" %}: {{ patient.gender }}</p>
                        <p class="text-gray-600">{% translate "Added by" %}: {{ patient.creator.personnel_id }}</p>
                        <p class="text-gray-600">{% translate "Added at" %}: {{ patient.created_at }}</p>
                        {{ patient.current_stay }}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h2 class="text-center">{% translate "You do not have permission view patient data. To do so, please log in." %}</h2>
        {% endif %}
    </div>
{% endblock content %}