ycms/cms/models/patient.py
from datetime import datetime

from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from ..constants import gender, insurance_types, record_types
from .abstract_base_model import AbstractBaseModel
from .timetravel_manager import current_or_travelled_time, TimetravelManager
from .user import User


class Patient(AbstractBaseModel):
    """
    Data model representing a Patient.
    """

    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=current_or_travelled_time, null=False)
    updated_at = models.DateTimeField(auto_now=True, null=False)
    insurance_type = models.BooleanField(
        verbose_name=_("insurance type"),
        help_text=_("Whether the patient is privately insured or not"),
        choices=insurance_types.CHOICES,
        default=insurance_types.STATUTORY,
    )
    first_name = models.CharField(
        max_length=32,
        verbose_name=_("first name"),
        help_text=_("First name of the patient"),
    )
    last_name = models.CharField(
        max_length=64,
        verbose_name=_("last name"),
        help_text=_("Last name of the patient"),
    )
    gender = models.CharField(
        max_length=1,
        choices=gender.CHOICES,
        verbose_name=_("gender"),
        help_text=_("Gender of the patient"),
        default=None,
    )
    date_of_birth = models.DateField(
        verbose_name=_("date of birth"), help_text=_("Date of birth of the patient")
    )
    _first = models.CharField(max_length=32, blank=True)
    _last = models.CharField(max_length=64, blank=True)

    objects = TimetravelManager()

    @cached_property
    def age(self):
        """
        Helper property to get the patient's age in years

        :return: the patient's age in years
        :rtype: int
        """
        today = datetime.today().date()
        years_ago = today.year - self.date_of_birth.year
        if today.month < self.date_of_birth.month or (
            today.month == self.date_of_birth.month
            and today.day < self.date_of_birth.day
        ):
            return max(0, years_ago - 1)
        return max(0, years_ago)

    @cached_property
    def insurance_name(self):
        """
        Helper property to get the human-readable representation of the patient's
        insurance type
        """
        return dict(insurance_types.CHOICES)[self.insurance_type]

    @cached_property
    def short_info(self):
        """
        Helper property to get a short info string about the patient

        :return: the patient's info as a short string
        :rtype: str
        """
        age = _("age")
        insurance = _("insurance")
        return f"{self.first_name[0]}. {self.last_name} ({age}: {self.age}, {insurance}: {self.insurance_name})"

    @cached_property
    def current_stay(self):
        """
        Helper property for accessing the patient's current hospital stay

        :return: the current bed assignment
        :rtype: ~ycms.cms.models.bed_assignment.BedAssignment
        """
        hospital_stay = self.medical_records.filter(
            models.Q(record_type=record_types.INTAKE)
            & models.Q(bed_assignment__admission_date__lte=current_or_travelled_time())
            & (
                models.Q(bed_assignment__discharge_date__isnull=True)
                | models.Q(
                    bed_assignment__discharge_date__gt=current_or_travelled_time()
                )
            )
        ).first()
        return hospital_stay.bed_assignment.get() if hospital_stay else None

    @cached_property
    def current_bed(self):
        """
        Helper property for accessing the patient's current bed

        :return: the current bed
        :rtype: ~ycms.cms.models.bed.Bed
        """
        return self.current_stay.bed if self.current_stay else None

    @cached_property
    def current_room(self):
        """
        Helper property for accessing the patient's current room

        :return: the current room
        :rtype: ~ycms.cms.models.room.Room
        """
        return self.current_bed.room if self.current_bed else None

    @cached_property
    def current_ward(self):
        """
        Helper property for accessing the patient's current ward

        :return: the current ward
        :rtype: ~ycms.cms.models.ward.Ward
        """
        return self.current_room.ward if self.current_room else None

    @staticmethod
    def _get_date_status(date_to_check):
        """
        Helper function to get the date status of a given date

        :param date_to_check: the date to check
        :type date_to_check: datetime.date
        :return: the date status
        :rtype: str
        """
        if not date_to_check:
            return None

        today = _("today")
        days_ago = _("{} days ago")
        day_ago = _("{} day ago")
        in_days = _("in {} days")
        in_day = _("in {} day")

        if not (
            days_since := (
                current_or_travelled_time().date() - date_to_check.date()
            ).days
        ):
            return f'{date_to_check.strftime("%b. %d, %Y")} ({today})'

        if days_since > 0:
            return f"{date_to_check.strftime('%b. %d, %Y')} ({ day_ago.format(days_since) if days_since == 1 else days_ago.format(days_since)})"

        days_until = abs(days_since)
        return f"{date_to_check.strftime('%b. %d, %Y')} ({in_day.format(days_until) if days_until == 1 else in_days.format(days_until)})"

    @cached_property
    def current_admission_date(self):
        """
        Helper property for accessing the patient's current admission date

        :return: the current admission date
        :rtype: str
        """
        if not self.current_stay:
            return None
        return self._get_date_status(self.current_stay.admission_date)

    @cached_property
    def current_discharge_date(self):
        """
        Helper property for accessing the patient's current discharge date

        :return: the current discharge date
        :rtype: str
        """
        if not self.current_stay:
            return None
        return self._get_date_status(self.current_stay.discharge_date)

    def __str__(self):
        """
        This overwrites the default Django :meth:`~django.db.models.Model.__str__` method which would return ``Patient object (id)``.
        It is used in the Django admin backend and as label for ModelChoiceFields.

        :return: A readable string representation of the patient
        :rtype: str
        """
        return f"{self.last_name}, {self.first_name} (patient {self.id})"

    def get_repr(self):
        """
        This overwrites the default Django ``__repr__()`` method which would return ``<Patient: Patient object (id)>``.
        It is used for logging.

        :return: The canonical string representation of the patient
        :rtype: str
        """
        return f"<Patient (id: {self.id})>"

    class Meta:
        verbose_name = _("patient")
        verbose_name_plural = _("patients")

ycms/cms/models/user.py
# Copyright [2019] [Integreat Project]
# Copyright [2023] [YCMS]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    Group,
    PermissionsMixin,
)
from django.core.exceptions import PermissionDenied
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from ..constants import group_names, job_types
from .abstract_base_model import AbstractBaseModel


class CustomUserManager(BaseUserManager):
    """
    This manager provides custom methods for user creation
    """

    def create_user(
        self,
        creator,
        personnel_id,
        email,
        group,
        assigned_ward=None,
        is_active=False,
        **extra_fields,
    ):
        """
        Create a new user and ensure they are added to the correct group (if any)

        :param creator: the user who attempts to create this new user
        :type creator: ~ycms.cms.models.user.User

        :param personnel_id: employee's ID
        :type personnel_id: int

        :param email: email address of the user, also used in lieu of username
        :type email: str

        :param group: one of :attr:`~ycms.cms.constants.group_names.CHOICES`
        :type group: str

        :param assigned_ward: the ward this user is assigned to or None
        :type assigned_ward: ~ycms.cms.models.ward.Ward

        :param is_active: Whether this user should be active
        :type is_active: bool

        :param extra_fields: additional fields
        :type extra_fields: dict

        :return: the newly created user
        :rtype: ~ycms.cms.models.users.user.User
        """
        # Check that no user is able to create over-privileged new users
        if not self.filter(id=creator.id).exists() or not (
            creator.is_superuser
            or str(group)
            in dict(group_names.IS_CREATABLE_BY[str(creator.group)]).keys()
        ):
            raise PermissionDenied()

        email = self.normalize_email(email)
        user = self.model(
            creator=creator,
            personnel_id=personnel_id,
            email=email,
            assigned_ward=assigned_ward,
            is_active=is_active,
            **extra_fields,
        )

        user.set_password(None)
        user.save(using=self._db)

        user.groups.add(Group.objects.get(name=group))
        user.save()

        return user

    def create_superuser(self, personnel_id, email, password=None, **extra_fields):
        """
        Create a new super user

        :param personnel_id: employee's ID
        :type personnel_id: int

        :param email: email address of the user, also used in lieu of username
        :type email: str

        :param password: user password
        :type password: str

        :param extra_fields: additional fields
        :type extra_fields: dict

        :return: the newly created user
        :rtype: ~ycms.cms.models.users.user.User
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(personnel_id, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin, AbstractBaseModel):
    """
    A custom User model that replaces the default Django User model.
    """

    creator = models.ForeignKey(
        "self", null=True, blank=True, on_delete=models.SET_NULL
    )
    created_at = models.DateTimeField(default=timezone.now, null=False)
    updated_at = models.DateTimeField(auto_now=True, null=False)
    personnel_id = models.CharField(
        null=True,
        unique=True,
        verbose_name=_("personnel ID"),
        help_text=_(
            "Employment ID number of the hospital staff. Used for authentication."
        ),
        max_length=10,
        validators=[MinLengthValidator(10)],
    )
    email = models.EmailField(
        unique=True,
        verbose_name=_("email"),
        help_text=_("Valid email address for this user"),
    )
    job_type = models.CharField(
        null=True,
        max_length=16,
        verbose_name=_("job type"),
        help_text=_("Job type of the employee"),
        choices=job_types.CHOICES,
    )
    first_name = models.CharField(
        null=True,
        max_length=32,
        verbose_name=_("first name"),
        help_text=_("First name of the employee"),
    )
    last_name = models.CharField(
        null=True,
        max_length=64,
        verbose_name=_("last name"),
        help_text=_("Last name of the employee"),
    )
    assigned_ward = models.ForeignKey(
        "cms.Ward",
        null=True,
        blank=True,
        verbose_name=_("Ward"),
        help_text=_("Ward this employee is assigned to (if any)"),
        on_delete=models.SET_NULL,
    )
    ward_as_timeline = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = "personnel_id"
    REQUIRED_FIELDS = ["email", "job_type", "first_name", "last_name"]

    @cached_property
    def group(self):
        """
        Return the primary group of this user

        :return: The first group of this user
        :rtype: ~django.contrib.auth.models.Group
        """
        return self.groups.first()

    @cached_property
    def group_name(self):
        """
        Return the human-readable group of this user

        :return: The group of this user
        :rtype: str
        """
        if not self.group:
            return "Root"
        return dict(group_names.CHOICES)[self.group.name]

    @cached_property
    def title(self):
        """
        Return the title of this user

        :return: The title of this user
        :rtype: str
        """
        return dict(job_types.CHOICES)[self.job_type]

    def __str__(self):
        """
        This overwrites the default Django :meth:`~django.db.models.Model.__str__` method which would return ``User object (id)``.
        It is used in the Django admin backend and as label for ModelChoiceFields.

        :return: A readable string representation of the user
        :rtype: str
        """
        return f"{self.job_type} {self.first_name} {self.last_name}"

    def get_repr(self):
        """
        This overwrites the default Django ``__repr__()`` method which would return ``<User: User object (id)>``.
        It is used for logging.

        :return: The canonical string representation of the user
        :rtype: str
        """
        fields = [
            f"id: {self.id}",
            f"personnel_id: {self.personnel_id}",
            f"email: {self.email}",
            f"job_type: {self.job_type}",
            f"first_name: {self.first_name}",
            f"last_name: {self.last_name}",
            f"group: {self.groups.first()}",
            f"is_staff: {self.is_staff}",
        ]
        return f"<User ({', '.join(fields)})>"

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")
        ordering = ["personnel_id"]
        default_permissions = ("add", "change", "delete", "view")

ycms/cms/forms/patient_form.py
import logging

from django import forms

from ..models import Patient
from .custom_model_form import CustomModelForm

logger = logging.getLogger(__name__)


class PatientForm(CustomModelForm):
    """
    Form for creating patients
    """

    class Meta:
        """
        This class contains additional meta configuration of the form class, see the :class:`django.forms.ModelForm`
        for more information.
        """

        model = Patient
        fields = [
            "first_name",
            "last_name",
            "gender",
            "date_of_birth",
            "insurance_type",
        ]
        widgets = {
            "date_of_birth": forms.NumberInput(attrs={"type": "date"}),
            "gender": forms.RadioSelect(),
            "insurance_type": forms.RadioSelect(),
        }

ycms/cms/views/patients/__init__.py
"""
This package contains views related to patients
"""
from .assign_view import AssignPatientView
from .discharge_view import DischargePatientView
from .intake_form_view import IntakeFormView
from .patient_details_view import (
    IntakeUpdateView,
    PatientDetailsView,
    PlannedStayCancelView,
    RecordCreateView,
)
from .patients_list_view import (
    PatientCreateView,
    PatientDeleteView,
    PatientsListView,
    PatientUpdateView,
)
from .update_patient_stay_view import UpdatePatientStayView

ycms/cms/templates/patients/hospital_stay_form.html
{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% load render_bundle from webpack_loader %}
<div class="mb-4">
    <div class="rounded-lg border border-gray-300 bg-white p-4 shadow-md md:columns-3 h-full justify-between gap-4 dark:bg-gray-800 dark:border-gray-700">
        <form enctype="multipart/form-data"
              method="post"
              data-unsaved-warning
              action="{% url 'cms:protected:update_intake' stay.medical_record.id %}">
            {% csrf_token %}
            <div class="w-full break-inside-avoid">
                <h2 class="mb-4">{% translate "Medical details" %}</h2>
                {% for field in forms.0.visible_fields %}
                    <div class="break-inside-avoid">
                        <label class="mt-0" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {% render_field field %}
                        <div class="help-text">{{ field.help_text }}</div>
                    </div>
                {% endfor %}
                {% for hidden in forms.0.hidden_fields %}{{ hidden }}{% endfor %}
            </div>
            <div class="w-full break-inside-avoid">
                <h2 class="mb-4">{% translate "Organizational details" %}</h2>
                {% for field in forms.1 %}
                    <div class="break-inside-avoid">
                        <label class="mt-0" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {% render_field field %}
                        <div class="help-text">{{ field.help_text }}</div>
                    </div>
                {% endfor %}
            </div>
            <button type="submit" class="btn mt-4 w-full">{% translate "Save" %}</button>
        </form>
        {% if current %}
            <button type="submit"
                    form="discharge-{{ patient.current_stay.id }}"
                    class="w-full focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 rounded px-4 py-3 mt-4 dark:bg-red-600 dark:hover:bg-red-800 dark:focus:ring-red-900">
                <form hidden
                      id="discharge-{{ patient.current_stay.id }}"
                      method="post"
                      action="{% url "cms:protected:discharge_patient" patient.current_stay.id %}">
                    {% csrf_token %}
                </form>
                {% translate "Discharge now" %}
            </button>
            {% if stay.recommended_ward %}
                <a href="{% url 'cms:protected:assign_patient' ward_id=stay.recommended_ward.id assignment_id=stay.id %}"
                   class="w-full block mt-4 text-white bg-green-500 hover:bg-green-700 focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-700 rounded px-4 py-3 text-center">
                    {% if stay.bed %}
                        {% translate "Transfer" %}
                    {% else %}
                        {% translate "Assign bed" %}
                    {% endif %}
                </a>
            {% endif %}
        {% else %}
            <button type="submit"
                    form="cancel-{{ stay.id }}"
                    class="w-full focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 rounded px-4 py-3 mt-4 dark:bg-red-600 dark:hover:bg-red-800 dark:focus:ring-red-900">
                {% translate "Cancel planned stay" %}
                <form hidden
                      id="cancel-{{ stay.id }}"
                      method="post"
                      action="{% url "cms:protected:cancel_stay" stay.id %}">
                    {% csrf_token %}
                </form>
            </button>
        {% endif %}
    </div>
</div>

ycms/cms/templates/patients/patient_card_wrapper.html
{% extends "_base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block title %}
    {% translate "Edit Patient Stay" %}
{% endblock title %}
{% block content %}
    {% with standalone_mode=True %}
        {% include "patients/patient_card.html" %}
    {% endwith %}
{% endblock content %}

ycms/cms/templates/patients/patient_details.html
{% extends "_base.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% load render_bundle from webpack_loader %}
{% block title %}
    {{ patient.first_name }} {{ patient.last_name }}
{% endblock title %}
{% block content %}
    {% if perms.cms.view_patient %}
        <div class="w-full flex flex-col flex-wrap mb-6">
            <h1 class="heading">{{ patient.first_name }} {{ patient.last_name }} ({{ patient.gender }}, {{ patient.age }})</h1>
        </div>
        <div class="rounded-lg border border-gray-300 bg-white p-4 shadow-md flex flex-col h-full dark:bg-gray-800 dark:border-gray-700">
            <form class="md:columns-3"
                  enctype="multipart/form-data"
                  method="post"
                  action="{% url "cms:protected:update_patient" patient.pk %}"
                  data-unsaved-warning>
                {% csrf_token %}
                {% for field in patient_form %}
                    <div class="break-inside-avoid radio-row">
                        <label class="mt-0" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {% render_field field %}
                        <div class="help-text">{{ field.help_text }}</div>
                    </div>
                {% endfor %}
                <button type="submit" class="btn mt-8 w-full">{% translate "Save" %}</button>
            </form>
        </div>
        {% if patient.current_stay %}
            <div class="w-full flex flex-col flex-wrap my-6">
                <h1 class="heading">{% translate "Current hospital stay" %}</h1>
            </div>
            {% with stay=patient.current_stay forms=current_stay_forms current=True %}
                {% include "patients/hospital_stay_form.html" %}
            {% endwith %}
        {% endif %}
        <div class="w-full md:flex my-6 items-center justify-between">
            <h1 class="heading">{% translate "Planned hospital stays" %}</h1>
            <a href="{% url "cms:protected:intake" %}?next=details&patient={{ patient.id }}"
               class="text-white bg-green-500 border-2 border-green-500 hover:bg-green-700 hover:border-green-700 rounded px-4 py-2 mt-2 md:mt-0 block md:inline">+ {% translate "Plan new stay" %}</a>
        </div>
        {% for stay, forms in planned_stays %}
            {% with stay=stay forms=forms current=False %}
                {% include "patients/hospital_stay_form.html" %}
            {% endwith %}
        {% empty %}
            <span class="dark:text-gray-200">{% translate "No planned stays." %}</span>
        {% endfor %}
        <div class="w-full flex flex-col flex-wrap my-6">
            <h1 class="heading">{% translate "Medical history (by date descending)" %}</h1>
        </div>
        <div class="border-l-8 border-gray-300 dark:border-gray-700 pl-8">
            {% if perms.cms.add_user %}
                <span class="text-sm text-gray-500 ml-2">{% now "d.m.Y H:i" %}, {{ user.title }} {{ user.first_name }} {{ user.last_name }}</span>
                <form class="rounded-lg border border-gray-300 bg-white p-4 shadow-md relative mb-4 md:flex dark:bg-gray-800 dark:border-gray-700 items-start gap-4"
                      enctype="multipart/form-data"
                      method="post"
                      action="{% url "cms:protected:create_record" patient.pk %}"
                      data-unsaved-warning>
                    {% csrf_token %}
                    <div class="absolute -left-12 top-0 bg-gray-300 dark:bg-gray-700 rounded-full h-6 w-6"></div>
                    <div class="flex-1">
                        <label class="mt-0" for="{{ record_form.record_type.id_for_label }}">{{ record_form.record_type.label }}</label>
                        {% render_field record_form.record_type class+="max-h-[165px]" %}
                        <div class="help-text">{{ record_form.record_type.help_text }}</div>
                        <label class="mt-0" for="{{ record_form.diagnosis_code.id_for_label }}">{{ record_form.diagnosis_code.label }}</label>
                        {% render_field record_form.diagnosis_code class+="max-h-[165px]" %}
                        <div class="help-text">{{ record_form.diagnosis_code.help_text }}</div>
                    </div>
                    <div class="flex-1">
                        <label class="mt-0" for="{{ record_form.note.id_for_label }}">{{ record_form.note.label }}</label>
                        {% render_field record_form.note class+="max-h-[165px]" %}
                        <div class="help-text">{{ record_form.note.help_text }}</div>
                    </div>
                    <button type="submit" class="btn mt-8 w-full flex-1">{% translate "Create" %}</button>
                </form>
            {% endif %}
            {% for record in records %}
                <span class="text-sm text-gray-500 ml-2">{{ record.created_at|date:"d.m.Y H:i" }}, {{ record.creator.title }} {{ record.creator.first_name }} {{ record.creator.last_name }}</span>
                <div class="rounded-lg border border-gray-300 bg-white p-4 shadow-md relative mb-4 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-200">
                    <div class="absolute -left-12 top-0 bg-gray-300 dark:bg-gray-700 rounded-full h-6 w-6"></div>
                    <table>
                        <tr class="block md:table-row">
                            <td class="block md:table-cell font-bold text-gray-500 pr-2">{% translate "Record type" %}:</td>
                            <td>{{ record.record_name }}</td>
                        </tr>
                        {% if record.diagnosis_code %}
                            <tr class="block md:table-row">
                                <td class="block md:table-cell font-bold text-gray-500 pr-2">{% translate "Diagnosis" %}:</td>
                                <td>{{ record.diagnosis_code.code }} ({{ record.diagnosis_code.description }})</td>
                            </tr>
                        {% endif %}
                        {% if record.note %}
                            <tr class="block md:table-row">
                                <td class="block md:table-cell font-bold text-gray-500 pr-2">{% translate "Note" %}:</td>
                                <td>{{ record.note }}</td>
                            </tr>
                        {% endif %}
                        {% if record.bed_assignment.get %}
                            {% with stay=record.bed_assignment.get %}
                                <tr class="block md:table-row">
                                    <td class="block md:table-cell font-bold text-gray-500 pr-2 pt-4">{% translate "Admission" %}:</td>
                                    <td class="md:pt-4">{{ stay.admission_date }}</td>
                                </tr>
                                <tr class="block md:table-row">
                                    <td class="block md:table-cell font-bold text-gray-500 pr-2">{% translate "Discharge" %}:</td>
                                    <td>
                                        {% if stay.discharge_date %}
                                            {{ stay.discharge_date }}
                                        {% else %}
                                            -
                                        {% endif %}
                                    </td>
                                </tr>
                                <tr class="block md:table-row">
                                    <td class="block md:table-cell font-bold text-gray-500 pr-2">{% translate "Bed" %}:</td>
                                    <td>
                                        {% if stay.bed %}
                                            {{ stay.bed.room.ward.name }}, {% translate "Room" %} {{ stay.bed.room.room_number }}, {% translate "Bed" %} {{ stay.bed.id }} ({% translate "Type" %}: {{ stay.bed.bed_type_name }})
                                        {% else %}
                                            -
                                        {% endif %}
                                    </td>
                                </tr>
                                <tr class="block md:table-row">
                                    <td class="block md:table-cell font-bold text-gray-500 pr-2">{% translate "Accompanied" %}:</td>
                                    <td>
                                        {% if stay.accompanied %}
                                            <i icon-name="check" class="w-4 h-4"></i>
                                        {% else %}
                                            <i icon-name="x" class="w-4 h-4"></i>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endwith %}
                        {% endif %}
                    </table>
                    {% if not record.bed_assignment.get and record.record_type == "intake" %}
                        <span class="italic text-gray-500">{% translate "No hospital stay data is associated with this intake. Most likely, the stay was cancelled in advance." %}</span>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock content %}